# Generated by Django 5.0.2 on 2024-03-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dtnasc', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=5)),
                ('genero', models.CharField(max_length=5)),
            ],
        ),
    ]
